### ISSUE TITLE
working with ggplot2 v 2.0.0

### ISSUE THREAD

**Issue by markrt** [dill/emoGG#10]
(This works fine on one machine, but I've just reinstalled R etc on my other machine, leading to the following)

I've recently reinstalled everything related to R on this machine, and have installed ggplot2 from CRAN. When I try to install emoGG, I get the following:

* installing *source* package 'emoGG' ...
** R
** inst
** preparing package for lazy loading
Error : package 'ggplot2' 2.0.0 was found, but == 1.0.1 is required by 'emoGG'
ERROR: lazy loading failed for package 'emoGG'
* removing 'C:/misc_directories/emoGG'
Error: Command failed (1)

**Comment by dill** [comment]
Are you installing emoGG from the master branch or the new-ggplot 
branch? You need the latter with the version of ggplot2 now on CRAN.


I need to switch this over this week...

**Comment by markrt** [comment]
Resolved with the update!
