### ISSUE TITLE
Use custom image in place of emoji

### ISSUE THREAD

**Issue by sfirke** [dill/emoGG#11]
Love this package. I'd have even more fun importing my own images... company logo, internet memes, etc.  There seems to be demand for this based on http://stackoverflow.com/questions/27637455/is-it-possible-to-display-custom-image-say-png-format-as-geom-point-in-r-ggplo and http://gis.stackexchange.com/questions/118286/is-it-possible-to-create-a-scatterplot-with-icons-svg-or-png-instead-of-points.

Seems like this package has much of the infrastructure already in place to add this functionality (e.g., specify a custom filepath or URL to image in place of an emoji value).

Thoughts?  Is this too much scope drift for the package?

**Comment by dill** [comment]
Glad to hear that you're enjoying it! I'm somewhat hesitant to have this drift into generic plotting of images in `ggplot2`.

If you're interested in doing this, I think more general code can be found in @sckott's [`rphylopic` package](https://github.com/sckott/rphylopic/) which might be easier to hack on. See [`add_phylopic`](https://github.com/sckott/rphylopic/blob/master/R/add_phylopic.r) -- this just relies on `annotation_custom` and `rasterGrob`.

Hope this helps! :rocket: :+1: :stars:
