### ISSUE TITLE
airport Icon

### ISSUE THREAD

**Issue by rafapereirabr** [dill/emoGG#12]
Hi David. Thanks so much for the package! 

I just wanted to suggest that you incorporate this type of airport/airplane icon. I believe this would be very helpful for those of us who are using ggplot2 for mapping spatial data

<img src="https://www.theoriginaltour.com/media/1687/plane_iconsvg.png" width="100">

**Comment by jjvenky** [comment]
There are several Unicode airplanes:
U+2702 ✈
U+1F636 to U+1F6EC 🛦🛧🛨🛩🛪🛫🛬
Yours looks like a rotated version of U+1F6EA 🛪 (northeast-pointing airplane).

**Comment by rafapereirabr** [comment]
The codes you mentioned don't work here. Not sure what I'm doing wrong here. Help?

```
ggplot(iris, aes(Sepal.Length, Sepal.Width)) +  geom_emoji(emoji="1f6ea")
> Error: Not Found
```


These are the options I've found for `emoji_search("airplanes")`
```
>        emoji             code        keyword
>981      dash            1f4a8            air
>1841 airplane             2708        vehicle
>1842 airplane             2708 transportation
>1843 airplane             2708         flight
>1844 airplane             2708            fly
>1846     seat            1f4ba       airplane
>2031       es 1f1ea\\U0001f1f8          spain
>2032       es 1f1ea\\U0001f1f8           flag
>2033       es 1f1ea\\U0001f1f8         nation
>2034       es 1f1ea\\U0001f1f8        country
>2035       es 1f1ea\\U0001f1f8         banner
>2733        a            1f170     red-square
>2734        a            1f170       alphabet
>2735        a            1f170         letter
```

Also, is there a way to visualize all available emoji/code, something like a catalogue?

**Comment by dill** [comment]
Hi Rafael, hi Jason,

At the moment `emoGG` only implements the emojis provided by the Twitter emoji API. This is not the full set of unicode characters, e.g. the U+1F6EA airplane.

A full set of Twitter emojis is available at (e.g.) http://emojipedia.org/twitter/

I don't have any plans right now to extend to other gylphs (or emoji sets) but would welcome a pull request if anyone would like to contribute such features.

**Comment by jjvenky** [comment]
So the 2708 airplane does work, producing with this emoji http://emojipedia.org/airplane/

ggplot(iris, aes(Sepal.Length, Sepal.Width)) +  geom_emoji(emoji="2708")
