### ISSUE TITLE
not possible to set size of emoji 

### ISSUE THREAD

**Issue by rafapereirabr** [dill/emoGG#15]
Hi Miller,

Thanks for the `emoGG` library. It's really good!

Just a few months ago, I was using this library and back then I could set the size of the emoji. However,, since I've updated the library it returns this error:
 
`ggplot() + geom_emoji(data=mtcars, aes(gear, carb), emoji="1f170", size=0.5) `
 >Error: Not Found

**Comment by dill** [comment]
I'm afraid I'm not supporting emoGG any more. I recommend using 
https://github.com/GuangchuangYu/emojifont as it's being actively 
developed and has better support for advanced features.

**Comment by rafapereirabr** [comment]
Ok. Thanks!
