### ISSUE TITLE
ggplot2 2.0 compatibility

### ISSUE THREAD

**Issue by jdidion** [dill/emoGG#8]
This probably just involves changing DESCRIPTION.

**Comment by dill** [comment]
You'll need to use the other branch in this repo ([`new-ggplot2`](https://github.com/dill/emoGG/tree/new-ggplot2)) to use `emoGG` with `ggplot2` 2.0+. See also [this note](https://github.com/dill/emoGG#ggplot2-versions) and #3 for more info.

Do let me know if you have any other issues :)
