### ISSUE TITLE
FUN(X[[i]], ...) : arguments to layer() should be calls

### ISSUE THREAD

**Issue by pmoehr** [dill/emoGG#9]
I installed the newest geom_emoji package and the ggplot2 1.0.1 because I read that with the newest version of ggplot2 it won't work.

But I still get an error.
FUN(X[[i]], ...) : arguments to layer() should be calls

I work with a Mac, R Studio version 0.99.489 and R version 3.2.3

Any ideas what I need to do to add geo_emoji to my ggplot?

**Comment by dill** [comment]
Have you tried using the [`new-ggplot2` branch](https://github.com/dill/emoGG/tree/new-ggplot2) of the repository with the new version of `ggplot2`? I will be re-working the repo in the next few weeks to make that the default.

Let me know how that goes!

(Apologies for the tardiness of my reply.)
